import Head from 'next/head'
import { Inter } from '@next/font/google'
import styles from '@/styles/Home.module.css'
import Features from '../components/Features'
import Benefits from '../components/Benefits'
import Form from "../components/Form"
import Contact from "../components/Contact"
import Hero from '../components/Hero'
import Faq from './Faq'

const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  return (
    <>
      <Head>
        <title>Road Rescue & Maintenance Company</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="main">
            <Hero />
            <Benefits />
            <Form />
            <Features />
            <Faq />
            <Contact />
        </main>
    </>
  )
}
